# ---------------------------------------------------------------------------------------------------------------------
# SINGLE CREATION

# This command starts the containers in detached mode without rebuilding the images if they already exist
# docker-compose -p approval-service-single -f docker-compose-single.yml up -d

# This command rebuilds images even if they exist
# docker-compose -p approval-service-single -f docker-compose-single.yml up -d --build

# This command stops and removes containers and volumes
# docker-compose -p approval-service-single -f docker-compose-single.yml down -v

# ---------------------------------------------------------------------------------------------------------------------

services:

  approval-service-mongodb:
    image: mongo
    container_name: approval-service-mongodb
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=approval-service

    volumes:
      - ./data:/data/db
      - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    #    command: mongod -auth
    networks:
      - spring

  approval-mongo-express:
    image: mongo-express
    container_name: approval-service-express
    ports:
      - "8088:8088"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=approval-service-mongodb
    depends_on:
      - approval-service-mongodb
    networks:
      - spring

#volumes:
#  mongo-db:
#    driver: local


networks:
  spring:
    driver: bridge