# ---------------------------------------------------------------------------------------------------------------------
# SINGLE CREATION

# This command starts the containers in detached mode without rebuilding the images if they already exist
# docker-compose -p user-service-single -f docker-compose-single.yml up -d

# This command rebuilds images even if they exist
# docker-compose -p user-service-single -f docker-compose-single.yml up -d --build

# This command stops and removes containers and volumes
# docker-compose -p user-service-single -f docker-compose-single.yml down -v

# DOCKER-COMPOSE FILE IS MEANT TO BE RUN ONCE

# ---------------------------------------------------------------------------------------------------------------------


version: '3.9'

services:

  user-service-postgres:
    image: postgres
    container_name: user-service-postgres-single
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user-service  # Comment if creating the database in the init.sql file

    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service-pgadmin:
    image: dpage/pgadmin4
    container_name: user-service-pgadmin4-single
    ports:
      - "8889:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password

networks:
  spring:
    driver: bridge