# ----------------------------------------------------

# This command starts the containers in detached mode without rebuilding the images if they already exist
# docker-compose -p comp3095-lala-ecommerse -f docker-compose.yml up -d

# This command rebuilds images even if they exist
# docker-compose -p comp3095-lala-ecommerse -f docker-compose.yml up -d --build

# ----------------------------------------------------


version: '3.9'

services:

  user-service-postgres:
    image: postgres
    container_name: user-service-postgres-single
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user-service

    volumes:
      - ./data/user:/data/db
      - ./init/user/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service-pgadmin:
    image: dpage/pgadmin4
    container_name: user-service-pgadmin4-single
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password


# Optional for persisting data
volumes:
  mongo-db:
    driver: local


networks:
  spring:
    driver: bridge